### ISSUE TITLE
On launch PP does not load in to a sidebar(horizontal or vertical) and will open to maximum window size

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#13] opened 2016-11-07 22:20 UTC
Manjaro 16.10 Qt5.7 Build 99d6f578c10710955e798663ed9619594132a860 
Testing via Appimage

How to reproduce: 
1. open scribus-indigo
2. Cancel' Open New Document' window
3. Press F2
Result: PP opens in dialog in the center of the screen
4. Double click dialog title 
Result: Expands the full length and width of the screen
5. Double click dialog title 
Result: returns to center of screen 
6. move dialog box to sidebar
Result: no sidebar is triggered

Diagnosis: When PP is open it opens in a separate window. I can see this because when I alt-tab to a different application I can still see the PP dialog visible outside of Scribus.

**Comment by luzpaz** [comment] 2016-11-07 22:23
Just noticed that in the terminal there is a error:
`QXcbConnection: XCB error: 3 (BadWindow), sequence: 699, resource id: 9055131, major code: 40 (TranslateCoords), minor code: 0`

**Comment by nitramr** [comment] 2016-11-15 11:46
I can't reproduce it on Ubuntu 16.04. Property panel is shown inside the dock.

**Comment by luzpaz** [comment] 2016-11-16 12:25
@gregp-scribus can you reproduce ?

**Comment by gregp-scribus** [comment] 2016-11-16 19:31
Not sure which version I'm using, but I don't see this. When I started it, my PP was in the left dock where I left it. I closed PP, closed Scribus and restarted. When I opened PP after restarting, it opened in the left dock.
My version is one or two before "Scribus Indigo Dock" was added to the About > Scribus dialog.

**Comment by nitramr** [comment] 2016-11-16 20:53
@gregp-scribus  sounds like the wanted behaviour. If you close  a panel and close Scribus afterwards the workspace will save for the next start.

If the behaviour is different it can help to delete the settings folder. Because in old settings file the data will store in another way for restoring. You can try it in the lates built from today: https://transfer.sh/153JzN/scribus-gita9d1218-glibc2.14-x86-64.appimage

**Comment by luzpaz** [comment] 2016-11-18 12:49
@nitramr i need to fix this ongoing issue of gtk3 and hidep problems on Manjaro to fully test this appropriately. Is there a way to start scribus up using a different prefs file or perhaps I should i nuke `~/.scribus/` ?

**Comment by nitramr** [comment] 2016-11-18 17:08
I can try to set a new settings path like ~/.scribus-indigo/

Scribus Indigo will store the settings there independent of the regular installed Scribus. Otherwise if you want to have a clean Scribus Indigo now, you can delete the whole settings folder (~/.scribus/). If you want to delete only the workspace settings remove following file in ~/.scribus/
- prefs150.xml

and following file for all other settings if needed:
- scribus150.rc

**Comment by gregp-scribus** [comment] 2016-11-18 17:20
And maybe save your original: mv .scribus .scribus.bak

**Comment by luzpaz** [comment] 2016-11-18 17:33
What would be nice is if https://bugs.scribus.net/view.php?id=13248 was implemented...especially for testers who are testing multiple builds

**Comment by gregp-scribus** [comment] 2016-11-19 21:21
What I see on Fedora 24/KDE is some pickiness that is involved with docking but not failure to dock. Even with switching back and forth from scribus-indigo and 1.5.3svn, I don't see either one messing up the other. 
When I start indigo the PP is docked to the left. If I drag it out, I usually can't get it dock somewhere else unless I let it go then click-drag again. The place that triggers the dock space to open is a little bit tricky but not irritating, since by sliding the PP around it will be found pretty easily.
One nice advantage of indigo is that in 1.5.3svn you can't enlarge the Outline window, but with indigo you can.

**Comment by nitramr** [comment] 2016-11-19 21:39
Yes, if you drag a panel out of a dock you can't dock it directly to an edge. You have to drop it to create a new container which you can dock on any edge you want. Or you can drop it in an existing dock container.

**Comment by luzpaz** [comment] 2016-11-21 13:02
> I can try to set a new settings path like ~/.scribus-indigo/

@nitramr do you mind creating this just for testing purposes? Then when indigo merges with trunk we can remove this?

**Comment by luzpaz** [comment] 2016-11-21 13:07
@nitramr or kill 2 birds with one stone and implement [#13248](https://bugs.scribus.net/view.php?id=13248) using latest trunk since @MrB74 latest commits:
* https://github.com/scribusproject/scribus/commit/465154e23a86b99d7a5fda2a2b1d65757c588f7d  
* https://github.com/scribusproject/scribus/commit/b27997ba7b8b3b03d159e9e5abe1e529ebf4efe6  
* https://github.com/scribusproject/scribus/commit/15c324a29580de8964dd350af206034fc2b66945  
* https://github.com/scribusproject/scribus/commit/c9113bcd5350e4aa2d7f5fa6d1257593bb2bcf31  
* https://github.com/scribusproject/scribus/commit/ca86b32fd14eca29a75c490efd42e5151fe0105b

**Comment by nitramr** [comment] 2016-11-21 13:34
Yes I mean a temporary fix while development. I will try to fix the params or think of better Solutions.

**Comment by nitramr** [comment] 2016-11-21 18:20
Oh my mistake, it is already fix :D. Ok, I will implement the fix.

**Comment by nitramr** [comment] 2016-11-21 20:04
I have add the latest code changes from 21st November. https://github.com/nitramr/scribus-indigo/commit/3d800ea5ae4d41c7ddbf594c78556417d2ebe398

**Comment by luzpaz** [comment] 2016-11-22 00:07
Awesome, @MrB74 just committed code for [#13248](https://bugs.scribus.net/view.php?id=13248) in https://github.com/scribusproject/scribus/commit/f8d0609dff024ce9efce72c283af2df67125be5d so perhaps we can modify the README to tell people to invoke scribus-indigo with the new prefs flag. I have yet to test it out.

**Comment by nitramr** [comment] 2016-12-06 21:05
I found the reason for floating panels in separate windows. Workspace load function can't handle panels which are not defined in prefs file. I have opened a new issue and will close this one.
https://github.com/nitramr/scribus-indigo/issues/34

**Closed as completed by nitramr** 2016-12-06 21:05 UTC
